# Generated by Django 3.1.1 on 2020-10-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200928_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='About me'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/icon/default_icon.jpg/', upload_to='profiles'),
        ),
    ]
